<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2013/07/03 21:23:30
return array (
  'dmWidgetContent' => 
  array (
    'title' => 
    array (
      'cache' => 'static',
    ),
    'link' => 
    array (
      'cache' => true,
    ),
    'text' => 
    array (
      'cache' => true,
    ),
    'image' => 
    array (
      'cache' => true,
    ),
  ),
  'dmWidgetNavigation' => 
  array (
    'breadCrumb' => 
    array (
      'cache' => true,
    ),
    'menu' => 
    array (
      'cache' => true,
    ),
  ),
  'dmWidgetSearch' => 
  array (
    'form' => 
    array (
      'cache' => true,
      'public_name' => 'Search form',
    ),
    'results' => 
    array (
      'cache' => false,
      'public_name' => 'Search results',
    ),
  ),
);
