<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/03 21:23:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=speeder;',
  'username' => 'speeder',
  'password' => 'speed123!',
  'name' => 'doctrine',
)),);
