<?php
// auto-generated by dmModuleManagerConfigHandler
// date: 2013/07/03 21:23:29
$manager = new dmModuleManager();
$modules = $projectModules = $modelModules = $types = array();
$types['Content'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Global'] = new dmModuleSpace();
$spaceModules = array();
$modules['main'] = $projectModules['main'] = $spaceModules['main'] = new dmProjectModule('main', $typeSpaces['Global'], array (
  'name' => 'Main',
  'plural' => 'Main',
  'model' => false,
  'credentials' => NULL,
  'underscore' => 'main',
  'plugin' => false,
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => array('header' => new dmModuleComponent('header', array (
  'name' => 'Header',
  'type' => 'simple',
)), 'footer' => new dmModuleComponent('footer', array (
  'name' => 'Footer',
  'type' => 'simple',
)), 'contenido' => new dmModuleComponent('contenido', array (
  'name' => 'Contenido',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => false,
  'sf_name' => 'main',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$typeSpaces['Global']->initialize('Global', $types['Content'], $spaceModules);
unset($spaceModules);
$types['Content']->initialize('Content', $typeSpaces);
unset($typeSpaces);
$types['Internal'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Page'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmPageView'] = $spaceModules['dmPageView'] = new dmModule('dmPageView', $typeSpaces['Page'], array (
  'name' => 'Dm page view',
  'plural' => 'Dm page views',
  'model' => 'DmPageView',
  'credentials' => NULL,
  'underscore' => 'dm_page_view',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmPageView',
));
$modelModules['DmPageView'] = 'dmPageView';
$modules['dmArea'] = $spaceModules['dmArea'] = new dmModule('dmArea', $typeSpaces['Page'], array (
  'name' => 'Dm area',
  'plural' => 'Dm areas',
  'model' => 'DmArea',
  'credentials' => NULL,
  'underscore' => 'dm_area',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmArea',
));
$modelModules['DmArea'] = 'dmArea';
$modules['dmZone'] = $spaceModules['dmZone'] = new dmModule('dmZone', $typeSpaces['Page'], array (
  'name' => 'Dm zone',
  'plural' => 'Dm zones',
  'model' => 'DmZone',
  'credentials' => NULL,
  'underscore' => 'dm_zone',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmZone',
));
$modelModules['DmZone'] = 'dmZone';
$modules['dmWidget'] = $spaceModules['dmWidget'] = new dmModule('dmWidget', $typeSpaces['Page'], array (
  'name' => 'Dm widget',
  'plural' => 'Dm widgets',
  'model' => 'DmWidget',
  'credentials' => NULL,
  'underscore' => 'dm_widget',
  'plugin' => 'dmCorePlugin',
  'overridden' => false,
  'has_admin' => false,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmWidget',
));
$modelModules['DmWidget'] = 'dmWidget';
$typeSpaces['Page']->initialize('Page', $types['Internal'], $spaceModules);
unset($spaceModules);
$types['Internal']->initialize('Internal', $typeSpaces);
unset($typeSpaces);
$types['System'] = new dmModuleType();
$typeSpaces = array();
$typeSpaces['Security'] = new dmModuleSpace();
$spaceModules = array();
$modules['dmUser'] = $projectModules['dmUser'] = $spaceModules['dmUser'] = new dmProjectModule('dmUser', $typeSpaces['Security'], array (
  'name' => 'User',
  'plural' => 'Users',
  'model' => 'DmUser',
  'credentials' => 'security_user',
  'underscore' => 'dm_user',
  'plugin' => 'dmUserPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => array('signin' => new dmModuleComponent('signin', array (
  'name' => 'Signin',
  'type' => 'simple',
)), 'form' => new dmModuleComponent('form', array (
  'name' => 'Register',
  'type' => 'form',
)), 'forgotPassword' => new dmModuleComponent('forgotPassword', array (
  'name' => 'Forgot password',
  'type' => 'simple',
)), ),
  'parent_key' => NULL,
  'has_page' => false,
  'sf_name' => 'dmUser',
  'children_keys' => 
  array (
  ),
  'path_keys' => 
  array (
  ),
));
$modelModules['DmUser'] = 'dmUser';
$modules['dmPermission'] = $spaceModules['dmPermission'] = new dmModule('dmPermission', $typeSpaces['Security'], array (
  'name' => 'Permission',
  'plural' => 'Permissions',
  'model' => 'DmPermission',
  'credentials' => 'security_permission',
  'underscore' => 'dm_permission',
  'plugin' => 'dmUserPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmPermission',
));
$modelModules['DmPermission'] = 'dmPermission';
$modules['dmGroup'] = $spaceModules['dmGroup'] = new dmModule('dmGroup', $typeSpaces['Security'], array (
  'name' => 'Group',
  'plural' => 'Groups',
  'model' => 'DmGroup',
  'credentials' => 'security_group',
  'underscore' => 'dm_group',
  'plugin' => 'dmUserPlugin',
  'overridden' => false,
  'has_admin' => true,
  'has_front' => true,
  'components' => 
  array (
  ),
  'sf_name' => 'dmGroup',
));
$modelModules['DmGroup'] = 'dmGroup';
$typeSpaces['Security']->initialize('Security', $types['System'], $spaceModules);
unset($spaceModules);
$types['System']->initialize('System', $typeSpaces);
unset($typeSpaces);
$manager->load($types, $modules, $projectModules, $modelModules);
unset($types, $modules, $projectModules, $modelModules);
return $manager;