<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/07/03 21:23:30
$this->security = array (
  'edittoggle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'tool_bar_front',
    ),
  ),
  'showtoolbartoggle' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'tool_bar_front',
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
