default:
  
  http_metas:
    content-type: text/html

  stylesheets:
    - bootstrap
    - style
    - nivo-slider
    - light

  javascripts:
    - front

  has_layout:     false
  layout:         layout